"execute pathogen#infect()
syntax on

filetype plugin indent on

set hidden
set hlsearch

if version >= 703
    set colorcolumn=80
endif

let g:miniBufExplCheckDupeBufs = 0
let g:miniBufExplVSplit = 30
let g:miniBufExplorerAutoStart = 0

set et
set ts=4
set sts=4
set sw=4
set nocp

noremap <C-\>t :TagbarToggle<CR>
nnoremap <C-\>t :TagbarToggle<CR>
noremap <C-\>n :NERDTreeToggle<CR>
nnoremap <C-\>n :NERDTreeToggle<CR>

"nmap <C-k>h :FSwitch<CR>

let g:ctrlp_cmd = 'CtrlPBuffer'
set background=dark

"map <F4> :execute "vimgrep /" . expand("<cword>") . "/j *.java" <Bar> cw<CR>

"let b:start_time=localtime()
"
"au BufRead,BufNewFile * let b:start_time=localtime()
"au CursorHold * call UpdateFile()
"" only write if needed and update the start time after the save
"function! UpdateFile()
"  if ((localtime() - b:start_time) >= 5)
"    update
"    let b:start_time=localtime()
"  else
"    echo "Only " . (localtime() - b:start_time) . " seconds have elapsed so far."
"  endif
"endfunction
"
"au BufWritePre * let b:start_time=localtime()

cmap w!! w !sudo tee % >/dev/null

"nnoremap <silent> <Leader>+ :exe "resize " . (winheight(0) * 3/2)<CR>
"nnoremap <silent> <Leader>- :exe "resize " . (winheight(0) * 2/3)<CR>

Bundle 'https://github.com/tomtom/vimtlib.git'
Bundle 'https://github.com/tomtom/tinykeymap_vim.git'
Bundle 'https://github.com/vim-scripts/taglist.vim.git'
Bundle 'https://github.com/brookhong/cscope.vim.git'
Bundle 'https://github.com/Rykka/riv.vim.git'

nnoremap <silent> <F8> :TlistToggle<CR>
nnoremap <silent> <Leader>x :bp\|bd #<CR>

"let g:cscope_cmd = 'pycscope'
"let g:pymode_lint_write = 1
let g:syntastic_check_on_wq = 0
let g:riv_global_leader = "<C-J>"

UnBundle 'AutoClose'
UnBundle 'spf13/vim-autoclose'
UnBundle 'vim-autoclose'
UnBundle 'eagletmt/ghcmod-vim'
UnBundle 'Shougo/vimproc'
