#!/bin/bash

bundle_id=com.adiumX.adiumX
#bundle_id=com.microsoft.Communicator

_dirname="/usr/bin/dirname"
_netstat="/usr/sbin/netstat"
_grep="/usr/bin/grep"
_notify="/usr/local/bin/terminal-notifier"
_gdate="/usr/local/bin/gdate"

D=$( (cd `dirname $0` >/dev/null; pwd -P) )

sleep_file="$D/check_ocs.sleeprec"

if [[ -f $sleep_file ]]; then

    sleep_expires=$(cat $sleep_file)
    current_time=$($_gdate +%s)

    if [[ $current_time -ge $sleep_expires ]]; then
        rm $sleep_file
    else
        exit 0
    fi
fi

msg="Hey, you're not connected to chat!"
group_id="groupid:chat.connection.checker"
title="Chat Connection Checker"

if ! $_netstat -p tcp | $_grep -q 'ly.*sip'; then
    $_notify \
        -message "$msg" \
        -activate $bundle_id \
        -group "$group_id" \
        -title "$title" \
        -appIcon "$D/communicator.png" \
        2>&1 >/dev/null
fi
