#!/usr/bin/env python3

import os
import sys

import configparser
c = configparser.ConfigParser()

c.read(os.path.expanduser(sys.argv[1]))

for section in c.sections():
    for key in c[section].keys():
        value = c[section][key]
        print(f"{section}.{key} = {value}")
